version: "3.8"

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./
        target: /app/docs
      - type: bind
        source: ./mkdocs.yml
        target: /app/mkdocs.yml
    restart: always
