site_name: book000/memo

repo_name: book000/memo
repo_url: https://github.com/book000/memo
edit_uri: edit/main/docs

copyright: 本サイト内に掲載された内容は当該ページやファイル内に特記のない限り、CC BY-SA 4.0 の元で利用できます。<br>All content on this site is available under CC BY-SA 4.0 unless otherwise noted in the relevant page or file.

nav:
  - Home: index.md
  - ... | os/**/*.md
  - ... | programming/**/*.md
  - ... | game/**/*.md
  - ... | etc/**/*.md
  - ...

theme:
  name: material
  language: ja
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - content.code.copy
  icon:
    logo: material/pencil-circle
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - admonition
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists:
      nested_indent: 2
  - attr_list
  - md_in_html

extra:
  search:
    language: ja
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/book000
    - icon: fontawesome/brands/github
      link: https://github.com/book000
  analytics:
    provider: google
    property: G-ESCN0DFTRB

extra_css:
  - css/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
      timezone: Asia/Tokyo
  - awesome-pages
  - glightbox
